"""Add receiver_id to Message model

Revision ID: 30a07260351a
Revises: 
Create Date: 2025-05-29 20:03:15.815239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a07260351a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_message_timestamp', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('read', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('delivered', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('seen', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'seen')
    op.drop_column('messages', 'delivered')
    op.drop_column('messages', 'read')
    op.drop_column('messages', 'conversation_id')
    op.drop_column('conversations', 'last_message_timestamp')
    # ### end Alembic commands ###
