"""add categories and books_categories tables

Revision ID: 66689b135fee
Revises: 
Create Date: 2025-08-04 16:28:28.024615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66689b135fee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'books_categories', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'exchanges', 'books', ['book_requested_id'], ['id'])
    op.create_foreign_key(None, 'exchanges', 'books', ['book_offered_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchanges', type_='foreignkey')
    op.drop_constraint(None, 'exchanges', type_='foreignkey')
    op.drop_constraint(None, 'books_categories', type_='foreignkey')
    # ### end Alembic commands ###
